DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  cost INT,
  is_deleted BOOLEAN DEFAULT 'false',
  comment VARCHAR(255)
);
