INSERT INTO items (title, description, cost) VALUES ('Stump', 'Might be a good seat...', 15)
INSERT INTO items (title, description, cost) VALUES ('Ace of Spades', 'Jackpot?', 48)
INSERT INTO items (title, description, cost) VALUES ('Generic Water Bottle', 'Quench your thirst', 23)
INSERT INTO items (title, description, cost) VALUES ('Desk Lamp', 'Are you afraid of the dark?', 99)
INSERT INTO items (title, description, cost) VALUES ('Rubber Ducky', 'Best Friend', 1)
INSERT INTO items (title, description, cost) VALUES ('Candy Wrapper', 'Timeless', 3)
INSERT INTO items (title, description, cost) VALUES ('Lightning Rod', '+4 Agility', 18)
INSERT INTO items (title, description, cost) VALUES ('Katana', '18 years and older', 77)